### ISSUE TITLE
[design and planning] // 했으면 thumbs up 표시

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#101]
@yankee624 
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#system-architecture
이미지에서 View, Model 양쪽에서 [Community, Article 관련된 것들] 삭제

API도 Food Recog, Recommendation API 삭제

**Comment by luvimperfection** [comment]
@yankee624 
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning/#model
[Community, Article 관련된 것들] 삭제

Notification모델에서
time, article_id 필드 삭제
item_id를 item_count_id로 변경

**Comment by luvimperfection** [comment]
@robotronic0694 
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#view
이미지 교체
community 삭제
Preference페이지 삭제
Noti도 페이지 형식 아님

**Comment by luvimperfection** [comment]
@robotronic0694 
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#frontend-components
 Basket, FindPassword, CommentList, Comment, Article*, Preference* 지워주세요

**Comment by luvimperfection** [comment]
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#frontend-relations
relation 그림 삽입해주세요

**Comment by luvimperfection** [comment]
@robotronic0694 
https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#frontend-algorithms

3. 
@형석: SelectItem 관련

라고 표시한 부분 변경

**Comment by robotronic0694** [comment]
> @robotronic0694
> https://github.com/swsnu/swpp2020-team1/wiki/Design-and-Planning#frontend-components
> Basket, FindPassword, CommentList, Comment, Article*, Preference* 지워주세요

CommentList와 Comment는 지우지 않는 것으로 결정

**Comment by robotronic0694** [comment]
All fixed, close the issue
