### ISSUE TITLE
expiration date 없는 item들

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#105]
유통기한 따로 없는 제품들의 경우
(1) AddItem.js에서
expiration date scanning 스킵하게 해줘야
(2) item edit화면에서 체크박스 ㅁ 표시

**Comment by luvimperfection** [comment]
onClickExpirationDateSkipButton
를 언급을 해놨었네 design & planning 에..

**Comment by robotronic0694** [comment]
figma UI 상
- expiration date scan할 수 있도록 추가
- item edit에 checkbox 추가 
완료.

**Comment by luvimperfection** [comment]
유통기한 없는 제품들: 
item edit에서 체크박스에 체크 시 expiration date input field disabled

**Comment by robotronic0694** [comment]
All specifications considered in Figma.

**Comment by yankee624** [comment]
백엔드에는 Notification model의 expire_date에 2999년 12월 31일로.
