### ISSUE TITLE
[ItemConfirm]UI

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#114]

**Comment by robotronic0694** [comment]
- UI 수정 완료
- automatic mode와 manual mode 자유롭게 이동 가능 (addItem에서 아무 것도 안해도 confirmItem 이동 가능)
- padding, margin 수정 완료

*** 수정해야 하는 부분 ***
- EditItem에서 한글 끊겨서 입력되는 현상 고치기
- EditItem에서 checkbox 해제하면 calender 버튼도 onclick 안먹게 하기
- footer의 완료, 카메라 버튼 UI 확정하고 margin 조절하기
