### ISSUE TITLE
[AddItem] UI

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#115]
현재: 
카메라 뷰 두개 크기 다름
바코드 스캐닝 카메라는 중앙에서 좌측으로 tilted되어있음 (why??)

**Comment by luvimperfection** [comment]
카메라 뷰 하나로 통일함

**Comment by yankee624** [comment]
- addItem에서 이름 입력 안하면 다음 사진 안 찍히도록만 하기. (ItemConfirm으로는 넘어갈 수 있음)
ItemConfirm에서 완료 누를 때 아이템 이름들 중에 빈 string 있는지 쭉 검사

- automatic mode <-> manual mode 자유롭게 왔다갔다 할 수 있게 (automatic에서 +버튼과 confirm 버튼을 하나로)

- addItem에서 아무것도 안해도 confirm item 넘어갈 수 있게?

**Comment by robotronic0694** [comment]
- UI 수정 완료
- automatic mode와 manual mode 자유롭게 이동 가능 (addItem에서 아무 것도 안해도 confirmItem 이동 가능)

* 수정해야 하는 부분
- addItem에서 이름 입력 안하고 expiration date 찍으려고 하면 toast로 이름 입력하라고 알려주기
- (optional) opacity 주고 사진 crop하기
- (optional) 사용 방법 안내
