### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#117]
문제?
backend에서 불러오는거 너무 느림

**Comment by yankee624** [comment]
시도해볼 것들
- cache 사용
- aws ec2 instance 더 좋은 거 사용

**Comment by luvimperfection** [comment]
// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
갓기창님 이건 머하는건가요 이거 머 하면 빨라지고 그런거 업나요

**Comment by yankee624** [comment]
시도해봐야겠네요 ^^
