### ISSUE TITLE
Expiration date 체크박스 + Backend 처리

### ISSUE THREAD

**Issue by yankee624** [swsnu/swpp2020-team1#136]
- EditItem에서 expiration_date에 체크박스 만들기
- 체크박스 풀면 expiration_date가 빈 string -> backend에서 빈 string받으면 2999년으로 처리
- frontend에서 2999년 받으면 빈 string으로 구현

**Comment by jsgh7276** [comment]
null 허용 검토. noti랑 충돌 검토

**Comment by jsgh7276** [comment]
Done
2999년 말고 2099/12/31로 저장, 프론트에서는 "-"로 표기. @yankee624 @luvimperfection @robotronic0694
