### ISSUE TITLE
[MainPage] 테스트 + UI 수정

### ISSUE THREAD

**Issue by jsgh7276** [swsnu/swpp2020-team1#149]
![image](https://user-images.githubusercontent.com/34760655/101063978-ce93d380-35d6-11eb-998c-3b37a156ea7e.png)

1. Noti icon이랑 sign out 겹침
2. 맨 밑이 약간 가려서 안보임

**Comment by yankee624** [comment]
아이템 눌렀을 때 뜨는 창 개같음

**Comment by luvimperfection** [comment]
헤더 빼고 그냥 상단에 signout만 넣어놓으면 됨

**Comment by luvimperfection** [comment]
signout는 그냥 아이콘 괜찮은거 찾아서 작게..

**Comment by yankee624** [comment]
- RecipeDetail page에도 logout 버튼 만들어놨는데 여기도 logout 구현 부탁!
- RecipeRecommend page에도 logout 버튼 만들어야 하나?
