### ISSUE TITLE
Mainpage Notification 버그

### ISSUE THREAD

**Issue by yankee624** [swsnu/swpp2020-team1#173]
- 아이템 추가 시 노티 아무것도 안 뜸 (맨 위 레시피노티 포함)
아이템 수량 변경 시 갑자기 한 번에 다 뜸
-

**Comment by luvimperfection** [comment]
MainPage 아이템 눌렀을 때 뜨는 창 (유통기한 여러개) 크기 늘리기 + 모바일에서도 확인하기

**Comment by jsgh7276** [comment]
유실된 코드 복구
