### ISSUE TITLE
Details

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#191]
@luvimperfection 
- [x] confirm 페이지에서 수정/완료 버튼 UI
- [x] confirm 페이지에서 카메라/완료 버튼 hover 시 글씨 안보임 => material ui로 갈아낌 / 이름 변경함 / 아이콘 넣음

**Comment by luvimperfection** [comment]
- [ ] recipe main page UI (메인페이지 느낌이랑 통일시키기)

**Comment by luvimperfection** [comment]
- [ ] 유통기한 retake 시 로딩

**Comment by luvimperfection** [comment]
- [ ] 회원가입 이후 첫 화면에 sample 아이템들 넣어놓기

**Comment by luvimperfection** [comment]
- [ ] 유통기한 두개 찍혔을때 어느걸로..

**Comment by luvimperfection** [comment]
- [ ] 재료가 1개 있을 때 마이너스(-)를 누르자마자 재료가 없어지는 것 보다는 없앨 것인지 확인시켜주는 창이 뜨는 것도 좋을 것 같아요

**Comment by luvimperfection** [comment]
- [ ] 모바일 크롬 브라우저 확인

**Comment by luvimperfection** [comment]
- [ ] 바코드인식률 개선 => 유저 뷰 사진 + nanonet api로 가는 사진 + 바코드 인식에 활용되는 사진 비교해서 분석

**Comment by yankee624** [comment]
- [ ] RecipeDetail UI 마무리

**Comment by luvimperfection** [comment]
- [ ] signin/up UI에 우리 앱 아이덴티티 컬러 좀 넣고..

**Comment by jsgh7276** [comment]
- [ ] NO INGREDIENTS HERE! PLEASE ADD YOURS -> 한글로

**Comment by luvimperfection** [comment]
- [ ] 앱 아이콘 (브라우저에서 리액트 아이콘 대신..)

**Comment by luvimperfection** [comment]
- [ ] Foodify 로고 png로 만들기 + 누르면 홈화면 가게 하기

**Comment by luvimperfection** [comment]
- [ ] 메인 페이지에 아이템 로딩 다 되기 전까지 스피너 넣기

**Comment by luvimperfection** [comment]
- [ ] 아이템 선택 후 preference 선택 탭이 올라왔을때, 빠져나올 방법이 없음 => 빠져나오게 x 버튼 추가

**Comment by luvimperfection** [comment]
- [ ] 바코드/유통기한 스킵 버튼

**Comment by jsgh7276** [comment]
noti creation time 추가

**Comment by jsgh7276** [comment]
- [ ] 안드로이드에서 국기 클릭할때 버튼 중첩 해결

**Comment by jsgh7276** [comment]
- [ ] '재료 선택하기' PC에서 버튼 사이즈 양옆으로 넘침

**Comment by luvimperfection** [comment]
- [ ] recipe recommend page : max width 설정했더니 배경 색깔의 진실이 드러남.. 배경grey카드white로 ui fix

**Comment by jsgh7276** [comment]
- [ ] preference 선택할 때 국기가 버튼 위에서 등장하는 문제 수정

**Comment by jsgh7276** [comment]
- [ ] 노티 없을 때 "알림이 없습니다"

**Comment by robotronic0694** [comment]
- [ ] addItem에서 뒤로 가기로 mainPage 넘어가면 reducer 내 item들이 reset되지 않음

**Comment by luvimperfection** [comment]
- [ ] 초기 안내 팝업
