### ISSUE TITLE
detailed checkups for backend

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#63]
Item.category가 null, blank 허용인가?
지금은   `blank=True, null=True` 로 되어있는데

**Comment by luvimperfection** [comment]
Item.barcode도 null, blank true인데 맞나
바코드 없는애들은 null로 처리하나 blank로 처리하나
그냥 이대로 둬도되나

**Comment by robotronic0694** [comment]
지금으로써는 category 개수가 적기 때문에 허용인데, 해결해야 하는 부분일 듯.
반면 barcode는 null 가능해야 할 것 같음.

사용자가 찍고 싶은 item에 해당하는 category가 존재하지 않을 때, 
이를 blank로 둘지 새로운 category를 만들 수 있게 할지는
그 부분 backend 고민해본 @yankee624 와 @jsgh7276 이 대답해야 할 듯 합니다.

**Comment by yankee624** [comment]
- 카테고리 리스트에 원하는 카테고리가 없을 수도 있기 때문에 "기타" 카테고리 만들기
- 유저가 카테고리 선택 안하고 넘기면 자동으로 "기타" 카테고리로 설정.
(즉, 백엔드에는 카테고리가 null/blank로 설정될 일은 없음)
