### ISSUE TITLE
Notification types

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#64]
[ex. expire, buy_item, recipe, ...]
노티 알림 유형을 어찌나눌것인지.. 유형이라는걸 두긴 할것인지 아무튼 조만간 확정지어야
(단순 유통기한 알림 ex. 3일 남았습니다!)
(제품 구매 연결 알림 ex. 우유가 곧 썩어요! 얼른 먹고 새로 주문할까요 ? ) (???) 
(레시피 알림 ex. 우유를 활용한 레시피 확인하러 고고)

**Comment by yankee624** [comment]
type
1. expire: 유통기한 3일 남았을 때. recipe로 연결.
2. buy_item: count가 줄어서 1개 됐을 때. 쿠팡 연결
3. recipe: 랜덤 재료 가지고 추천. 항상 한 개씩 위에 띄워놓기
3번은 backend에서 처리하지 않고, front에서 나머지 두 타입과 다른 색으로 띄워놓기.

**Comment by luvimperfection** [comment]
2. buy_item 구현하려면
메인페이지에서 버튼리스너에다가
줄어들어서 1되면 
noti/user/int:user_id/ 에 POST 날려주는..
(POST 추가)
