### ISSUE TITLE
item edit (AddItem, ItemConfirm) input verification

### ISSUE THREAD

**Issue by yankee624** [swsnu/swpp2020-team1#70]
name, expiration date, barcode_num, count에 대해 verification 진행
- name: not empty
- expiration date: YYYY/MM/DD
- barcode num:
- count: positive integer

**Comment by luvimperfection** [comment]
날짜도 밑에 달력UI띄워주고

아무튼 교수님은 UI를 중시하신다

**Comment by yankee624** [comment]
날짜: 달력 말고 드랍다운
name: not empty
만 하면 된다.

(barcode는 empty 가능해서 verification 필요없음, 
count는 - 눌러도 1 미만으로 안 떨어지게 만들기, 
category는 선택 안하면 자동으로 "기타"로 저장됨, 
expiration_date는 체크박스 풀면 자동으로 empty 되도록)

**Comment by yankee624** [comment]
expiration date를 empty string으로 넘겨주면 backend에서 그거 받아서 2999년 등으로 처리하도록 하기
