### ISSUE TITLE
Implement category

### ISSUE THREAD

**Issue by yankee624** [swsnu/swpp2020-team1#81]
- category reducer, action
- EditItem에서 GET category 해온 후 유저가 그 리스트에서 검색할 수 있도록 만들어주기
- (optional) item name으로부터 자동으로 카테고리 추천

**Comment by luvimperfection** [comment]
카테고리 리스트에 원하는 카테고리가 없을 수도 있기 때문에 "기타" 카테고리 만들기
유저가 카테고리 선택 안하고 넘기면 자동으로 "기타" 카테고리로 설정.
(즉, 백엔드에는 카테고리가 null/blank로 설정될 일은 없음)

**Comment by jsgh7276** [comment]
기타만 만들면 됨

**Comment by jsgh7276** [comment]
Implemented (should write test again)
