### ISSUE TITLE
Login/Logout

### ISSUE THREAD

**Issue by luvimperfection** [swsnu/swpp2020-team1#82]

**Comment by luvimperfection** [comment]
login/logout부터 구현!
(ensure csrf)
server에서 유저한테 토큰 보내줘서 authenticate

**Comment by luvimperfection** [comment]
nickname은 firstname같은걸로..

**Comment by luvimperfection** [comment]
frontend부터 만들고 back짜야지..

**Comment by luvimperfection** [comment]
프론트 그럴듯한거 주워서 맞춰놓음
수업끝나고 store action reducer  백엔드 연결하기

**Comment by luvimperfection** [comment]
signin signup 했음

signout 헤더구현 & 아이템 없는 유저들에 대한 처리 해줘야함 (mainpage에서 오류 바바박)

**Comment by luvimperfection** [comment]
LoginRoute로 갈아끼우기,
새로고침 대응 확인하기,
test짜기,
csrf 토큰 관련 처리 하기,
signout 헤더 구현하기,
MainPage에서 아이템 없는 유저들 처리 해주기

**Comment by yankee624** [comment]
Temporary users 없애고 제대로 된 유저로 처리 (RecipeDetail)

**Comment by luvimperfection** [comment]
[done]
LogInRouter로 모든 페이지 갈아끼고 새로고침 대응 확인
로그아웃버튼 헤더에 구현해놓음 (노티버튼을 헤더에다가 넣는게 낫나?)
로그아웃 누르면 로그인페이지로 가는거 확인
로그인하면 로그인페이지 가도 메인페이지로 가는거 확인
테스트코드 (signin, signup, logout) // 헤더는 빼놓음
[to be done]
MainPage/RecipeDetail 유저 제대로 갈아끼기
토큰처리하기
유저별로 아이템들 만들어서 잘 불러지는지 확인하기
