### ISSUE TITLE
[AddItem] bugs

### ISSUE THREAD

**Issue by yankee624** [swsnu/swpp2020-team1#86]
- 첫번째 아이템 expiration date 스캔 -> barcode 스캔 -> 두번 째 아이템 expiration date 스캔하면, 두번째 아이템 barcode 스캔이 스킵됨 (첫번째 아이템의 바코드가 똑같이 두번째 아이템에 입력됨)

- expiration date 스캔 -> barcode 스캔 -> expiration date/barcode retake -> barcode retake 하면 barcode retake가 무시됨

- 아무것도 스캔 안하고 ItemConfirm으로 넘어가면 빈 아이템이 하나 추가된 상태로 시작됨.

- 그 외에도 더 있을 수도. 리팩토링 필요

**Comment by luvimperfection** [comment]
AddItem.js
_onDetected 에서
axios.get(`/back/item/user/${user_id}/`)
이거 걍 유저 당 한번만 불러주면 됨

**Comment by yankee624** [comment]
ItemConfirm 갔다가 AddItem으로 가면 그동안 추가했던 아이템들 다 사라짐

**Comment by yankee624** [comment]
- 모바일에서 카메라 뷰 크기가 다름
